// Command server is the vianden-server entry point.
//
//	vianden-server              run the server
//	vianden-server healthcheck  exit 0 if the local server answers /api/v1/health (for Docker)
package main

import (
	"context"
	"fmt"
	"log/slog"
	"net"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"

	// Built-in list of trusted certificate authorities, used only when the system has none
	// (the Docker image contains nothing but this program). Needed to talk to Let's Encrypt.
	_ "golang.org/x/crypto/x509roots/fallback"

	"github.com/5cfp/vianden-server/internal/accounts"
	"github.com/5cfp/vianden-server/internal/api"
	"github.com/5cfp/vianden-server/internal/buildinfo"
	"github.com/5cfp/vianden-server/internal/chat"
	"github.com/5cfp/vianden-server/internal/config"
	"github.com/5cfp/vianden-server/internal/db"
	"github.com/5cfp/vianden-server/internal/files"
	"github.com/5cfp/vianden-server/internal/realtime"
	"github.com/5cfp/vianden-server/internal/supervisor"
	"github.com/5cfp/vianden-server/internal/tcpshare"
	"github.com/5cfp/vianden-server/internal/voice"
	"github.com/5cfp/vianden-server/internal/web"
)

func main() {
	if len(os.Args) > 1 && os.Args[1] == "healthcheck" {
		os.Exit(healthcheck())
	}

	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))
	if err := run(logger); err != nil {
		logger.Error("server stopped with an error", "error", err)
		os.Exit(1)
	}
}

func run(logger *slog.Logger) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	// ctx is cancelled when you press Ctrl+C (or the OS / Docker asks the process to stop).
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	logger.Info("starting vianden-server",
		"version", buildinfo.Version, "protocol_version", buildinfo.ProtocolVersion, "tls_mode", cfg.TLSMode)

	// The database must be reachable and up to date before we accept any requests.
	pool, err := db.Connect(ctx, cfg.DatabaseURL)
	if err != nil {
		return err
	}
	defer pool.Close()

	if err := db.Migrate(ctx, cfg.DatabaseURL, logger); err != nil {
		return err
	}

	// db.New and PostgresVersion are generated by sqlc from internal/db/queries/*.sql.
	pgVersion, err := db.New(pool).PostgresVersion(ctx)
	if err != nil {
		return err
	}
	logger.Info("connected to database", "postgres", pgVersion)

	accountService, setupToken, err := accounts.NewService(ctx, pool)
	if err != nil {
		return err
	}
	if setupToken != "" {
		printSetupToken(setupToken)
		logger.Warn("this server has no owner yet: register with the setup token printed above")
	}

	// The hub keeps all live (WebSocket) connections and pushes events to them.
	chatService := chat.NewService(pool)
	fileService, err := files.NewService(pool, cfg.DataDir)
	if err != nil {
		return err
	}
	hub := realtime.NewHub(logger)
	hub.SetChannelAccess(chatService.ChannelAccess) // typing only in channels the sender may see

	// Voice (M7). If it cannot start (e.g. the UDP port is taken), the server runs without
	// it: text chat must keep working.
	voiceService, iceTCP := startVoice(ctx, cfg, chatService, hub, logger)
	var voiceDep api.Voice
	if voiceService != nil {
		defer voiceService.Close()
		hub.SetVoice(voiceService)
		voiceDep = voiceService
	}

	handler := api.NewHandler(api.Deps{
		ServerName: cfg.ServerName,
		DB:         pool,
		Accounts:   accountService,
		Chat:       chatService,
		Files:      fileService,
		Profiles:   accountService,
		Avatars:    fileService,
		Voice:      voiceDep,
		Realtime:   hub,
		Logger:     logger,
	})

	// Each long-running service runs under its own supervisor, in parallel. If one fails,
	// it is restarted; the others keep running.
	var wg sync.WaitGroup
	wg.Go(func() {
		supervisor.Run(ctx, logger, "web", func(ctx context.Context) error {
			// Shutdown does not wait for WebSocket connections (they are "hijacked" from the
			// HTTP server), so hub.CloseAll closes them when shutting down.
			return web.Serve(ctx, cfg, handler, hub.CloseAll, iceTCP, logger)
		})
	})
	if voiceService != nil {
		wg.Go(func() {
			supervisor.Run(ctx, logger, "voice", voiceService.Run)
		})
	}
	wg.Go(func() {
		supervisor.Run(ctx, logger, "cleanup", func(ctx context.Context) error {
			return cleanupLoop(ctx, accountService, fileService, logger)
		})
	})
	wg.Wait()

	logger.Info("vianden-server stopped")
	return nil
}

// cleanupLoop runs once an hour: it deletes expired and logged-out sessions (so the table
// does not grow forever), and uploads that are no longer used (see files.Service.Cleanup).
func cleanupLoop(ctx context.Context, svc *accounts.Service, fileSvc *files.Service, logger *slog.Logger) error {
	ticker := time.NewTicker(time.Hour)
	defer ticker.Stop()
	for {
		n, err := svc.DeleteOldSessions(ctx)
		if err != nil {
			return err // the supervisor logs it and tries again later
		}
		if n > 0 {
			logger.Info("deleted old sessions", "count", n)
		}
		removed, err := fileSvc.Cleanup(ctx)
		if err != nil {
			return err
		}
		if removed > 0 {
			logger.Info("deleted unused upload files", "count", removed)
		}
		select {
		case <-ctx.Done():
			return nil
		case <-ticker.C:
		}
	}
}

// printSetupToken shows the one-time owner setup token on the console.
//
// This is the ONE place a secret is printed on purpose: the person who starts the server
// is by definition allowed to become its owner. The token is only usable until an owner
// exists, and a new one is made on every restart until then. It is printed directly,
// not through the logger, so it never ends up in structured log files.
func printSetupToken(token string) {
	fmt.Println()
	fmt.Println("==================================================================")
	fmt.Println("  FIRST-RUN SETUP: this server has no owner yet.")
	fmt.Println("  Register in the app and enter this as your invite code:")
	fmt.Println()
	fmt.Println("    " + token)
	fmt.Println()
	fmt.Println("  It works once. Keep it secret: whoever uses it becomes the owner.")
	fmt.Println("==================================================================")
	fmt.Println()
}

// startVoice opens the voice UDP port and the TCP fallback (which shares the main port).
// On failure it logs why and returns nils: the server then runs without voice.
func startVoice(ctx context.Context, cfg config.Config, chatService *chat.Service, hub *realtime.Hub, logger *slog.Logger) (*voice.Service, *tcpshare.Queue) {
	if cfg.VoiceUDPPort == 0 {
		logger.Info("voice is turned off (VIANDEN_VOICE_UDP_PORT=0)")
		return nil, nil
	}
	// The address is what voice tells clients for the TCP fallback: only its PORT is used
	// (the IPs come from the public address setting).
	iceTCP := tcpshare.NewQueue(&net.TCPAddr{Port: cfg.VoiceTCPPort})
	lookup := func(ctx context.Context, id int64) (voice.ChannelRules, bool) {
		c, ok := chatService.ChannelInfo(ctx, id)
		return voice.ChannelRules{View: c.ViewRole, Send: c.SendRole, Voice: c.Type == chat.TypeVoice}, ok
	}
	svc, err := voice.New(ctx, voice.Config{
		UDPPort: cfg.VoiceUDPPort, PublicAddresses: cfg.VoicePublicAddresses, TCP: iceTCP,
	}, lookup, hub, logger)
	if err != nil {
		logger.Error("voice is NOT available; text chat works normally", "error", err)
		iceTCP.Close()
		return nil, nil
	}
	return svc, iceTCP
}
