// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	UserID    int64
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name, password_hash, is_owner)
VALUES ($1, $2, $3, $4)
RETURNING id, username, display_name, password_hash, is_owner, created_at
`

type CreateUserParams struct {
	Username     string
	DisplayName  string
	PasswordHash string
	IsOwner      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsOwner,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsOwner,
		&i.CreatedAt,
	)
	return i, err
}

const lockUsableInvite = `-- name: LockUsableInvite :one
SELECT id, code_hash, created_by, max_uses, uses, expires_at, created_at FROM invites
WHERE code_hash = $1 AND uses < max_uses AND expires_at > now()
FOR UPDATE
`

// Finds an invite that is not expired or used up, and LOCKS its row until the
// transaction ends. Two people registering with the same last-use invite at the
// same moment then cannot both succeed: the second one waits, re-checks, and finds nothing.
func (q *Queries) LockUsableInvite(ctx context.Context, codeHash []byte) (Invite, error) {
	row := q.db.QueryRow(ctx, lockUsableInvite, codeHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const ownerExists = `-- name: OwnerExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE is_owner)
`

func (q *Queries) OwnerExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, ownerExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const useInvite = `-- name: UseInvite :exec
UPDATE invites SET uses = uses + 1 WHERE id = $1
`

func (q *Queries) UseInvite(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, useInvite, id)
	return err
}
