// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	UserID    int64
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name, password_hash, is_owner)
VALUES ($1, $2, $3, $4)
RETURNING id, username, display_name, password_hash, is_owner, created_at
`

type CreateUserParams struct {
	Username     string
	DisplayName  string
	PasswordHash string
	IsOwner      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsOwner,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsOwner,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldSessions = `-- name: DeleteOldSessions :execrows
DELETE FROM sessions WHERE expires_at < now() OR revoked_at IS NOT NULL
`

// Removes sessions that can never be used again: expired, or logged out.
func (q *Queries) DeleteOldSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT sessions.id, sessions.user_id, sessions.token_hash, sessions.created_at, sessions.last_used_at, sessions.expires_at, sessions.revoked_at, users.id, users.username, users.display_name, users.password_hash, users.is_owner, users.created_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.expires_at > now()
`

type GetActiveSessionRow struct {
	Session Session
	User    User
}

// Finds a session by token hash, only if it is not revoked and not expired, together with its user.
func (q *Queries) GetActiveSession(ctx context.Context, tokenHash []byte) (GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, tokenHash)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.CreatedAt,
		&i.Session.LastUsedAt,
		&i.Session.ExpiresAt,
		&i.Session.RevokedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.DisplayName,
		&i.User.PasswordHash,
		&i.User.IsOwner,
		&i.User.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, password_hash, is_owner, created_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsOwner,
		&i.CreatedAt,
	)
	return i, err
}

const lockUsableInvite = `-- name: LockUsableInvite :one
SELECT id, code_hash, created_by, max_uses, uses, expires_at, created_at FROM invites
WHERE code_hash = $1 AND uses < max_uses AND expires_at > now()
FOR UPDATE
`

// Finds an invite that is not expired or used up, and LOCKS its row until the
// transaction ends. Two people registering with the same last-use invite at the
// same moment then cannot both succeed: the second one waits, re-checks, and finds nothing.
func (q *Queries) LockUsableInvite(ctx context.Context, codeHash []byte) (Invite, error) {
	row := q.db.QueryRow(ctx, lockUsableInvite, codeHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const ownerExists = `-- name: OwnerExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE is_owner)
`

func (q *Queries) OwnerExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, ownerExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = now(), expires_at = $2 WHERE id = $1
`

type TouchSessionParams struct {
	ID        int64
	ExpiresAt time.Time
}

// Sliding expiry: a used session stays valid for another full lifetime.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}

const useInvite = `-- name: UseInvite :exec
UPDATE invites SET uses = uses + 1 WHERE id = $1
`

func (q *Queries) UseInvite(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, useInvite, id)
	return err
}
