// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"
	"time"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, topic, position)
VALUES ($1, $2, (SELECT COALESCE(MAX(position), -1) + 1 FROM channels))
RETURNING id, name, topic, type, position, created_at
`

type CreateChannelParams struct {
	Name  string
	Topic string
}

// New channels go to the end of the list.
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel, arg.Name, arg.Topic)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (channel_id, author_id, content)
VALUES ($1, $2, $3)
RETURNING id, channel_id, content, created_at
`

type CreateMessageParams struct {
	ChannelID int64
	AuthorID  *int64
	Content   string
}

type CreateMessageRow struct {
	ID        int64
	ChannelID int64
	Content   string
	CreatedAt time.Time
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ChannelID, arg.AuthorID, arg.Content)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, topic, type, position, created_at FROM channels WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT
    c.id, c.name, c.topic, c.type, c.position,
    -- sqlc cannot tell that a LATERAL join may find nothing, so make "no message" explicit.
    (lm.created_at IS NOT NULL)::boolean        AS has_last_message,
    COALESCE(lm.content, '')::text            AS last_content,
    COALESCE(lm.created_at, now())::timestamptz AS last_created_at,
    u.display_name AS last_author
FROM channels c
LEFT JOIN LATERAL (
    SELECT m.content, m.created_at, m.author_id
    FROM messages m
    WHERE m.channel_id = c.id
    ORDER BY m.id DESC
    LIMIT 1
) lm ON true
LEFT JOIN users u ON u.id = lm.author_id
ORDER BY c.position, c.id
`

type ListChannelsRow struct {
	ID             int64
	Name           string
	Topic          string
	Type           string
	Position       int32
	HasLastMessage bool
	LastContent    string
	LastCreatedAt  time.Time
	LastAuthor     *string
}

// All channels in room-list order, each with its newest message (if any) for the preview.
func (q *Queries) ListChannels(ctx context.Context) ([]ListChannelsRow, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsRow
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Topic,
			&i.Type,
			&i.Position,
			&i.HasLastMessage,
			&i.LastContent,
			&i.LastCreatedAt,
			&i.LastAuthor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT
    m.id, m.channel_id, m.content, m.created_at, m.author_id,
    u.username     AS author_username,
    u.display_name AS author_display_name
FROM messages m
LEFT JOIN users u ON u.id = m.author_id
WHERE m.channel_id = $1
  AND ($2::bigint IS NULL OR m.id < $2::bigint)
ORDER BY m.id DESC
LIMIT $3
`

type ListMessagesParams struct {
	ChannelID int64
	Before    *int64
	RowLimit  int32
}

type ListMessagesRow struct {
	ID                int64
	ChannelID         int64
	Content           string
	CreatedAt         time.Time
	AuthorID          *int64
	AuthorUsername    *string
	AuthorDisplayName *string
}

// One page of history, NEWEST first. "before" is the id of the oldest message the
// client already has (NULL for the newest page). Keyset pagination: see docs.
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ChannelID, arg.Before, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Content,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels SET name = $2, topic = $3 WHERE id = $1
RETURNING id, name, topic, type, position, created_at
`

type UpdateChannelParams struct {
	ID    int64
	Name  string
	Topic string
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel, arg.ID, arg.Name, arg.Topic)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
