// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"
	"time"
)

const addMentions = `-- name: AddMentions :exec
INSERT INTO message_mentions (message_id, user_id)
SELECT $1, unnest($2::bigint[])
ON CONFLICT DO NOTHING
`

type AddMentionsParams struct {
	MessageID int64
	UserIds   []int64
}

func (q *Queries) AddMentions(ctx context.Context, arg AddMentionsParams) error {
	_, err := q.db.Exec(ctx, addMentions, arg.MessageID, arg.UserIds)
	return err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, topic, view_role, send_role, type, position)
VALUES ($1, $2, $3, $4, $5, (SELECT COALESCE(MAX(position), -1) + 1 FROM channels))
RETURNING id, name, topic, type, position, created_at, view_role, send_role
`

type CreateChannelParams struct {
	Name     string
	Topic    string
	ViewRole string
	SendRole string
	Type     string
}

// New channels go to the end of the list.
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.Name,
		arg.Topic,
		arg.ViewRole,
		arg.SendRole,
		arg.Type,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.Position,
		&i.CreatedAt,
		&i.ViewRole,
		&i.SendRole,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (channel_id, author_id, content, reply_to_id, mentions_everyone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateMessageParams struct {
	ChannelID        int64
	AuthorID         *int64
	Content          string
	ReplyToID        *int64
	MentionsEveryone bool
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ChannelID,
		arg.AuthorID,
		arg.Content,
		arg.ReplyToID,
		arg.MentionsEveryone,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMentions = `-- name: DeleteMentions :exec
DELETE FROM message_mentions WHERE message_id = $1
`

func (q *Queries) DeleteMentions(ctx context.Context, messageID int64) error {
	_, err := q.db.Exec(ctx, deleteMentions, messageID)
	return err
}

const deleteMessage = `-- name: DeleteMessage :execrows
UPDATE messages SET content = '', deleted_at = now(), deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type DeleteMessageParams struct {
	ID        int64
	DeletedBy *int64
}

// Erases the text for real (not just hidden) and keeps a placeholder row.
func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessage, arg.ID, arg.DeletedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const editMessage = `-- name: EditMessage :execrows
UPDATE messages SET content = $3, mentions_everyone = $4, edited_at = now()
WHERE id = $1 AND author_id = $2 AND deleted_at IS NULL
`

type EditMessageParams struct {
	ID               int64
	AuthorID         *int64
	Content          string
	MentionsEveryone bool
}

// Only the author can edit, and only a live message.
func (q *Queries) EditMessage(ctx context.Context, arg EditMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, editMessage,
		arg.ID,
		arg.AuthorID,
		arg.Content,
		arg.MentionsEveryone,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, topic, type, position, created_at, view_role, send_role FROM channels WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.Position,
		&i.CreatedAt,
		&i.ViewRole,
		&i.SendRole,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT
    m.id, m.channel_id, m.content, m.created_at, m.edited_at, m.author_id,
    (m.deleted_at IS NOT NULL)::boolean AS deleted, m.mentions_everyone,
    u.username     AS author_username,
    u.display_name AS author_display_name,
    m.reply_to_id,
    r.content      AS reply_content,
    (r.deleted_at IS NOT NULL)::boolean AS reply_deleted,
    r.author_id    AS reply_author_id,
    ru.username     AS reply_author_username,
    ru.display_name AS reply_author_display_name
FROM messages m
LEFT JOIN users u ON u.id = m.author_id
LEFT JOIN messages r ON r.id = m.reply_to_id
LEFT JOIN users ru ON ru.id = r.author_id
WHERE m.id = $1 AND m.channel_id = $2
`

type GetMessageParams struct {
	ID        int64
	ChannelID int64
}

type GetMessageRow struct {
	ID                     int64
	ChannelID              int64
	Content                string
	CreatedAt              time.Time
	EditedAt               *time.Time
	AuthorID               *int64
	Deleted                bool
	MentionsEveryone       bool
	AuthorUsername         *string
	AuthorDisplayName      *string
	ReplyToID              *int64
	ReplyContent           *string
	ReplyDeleted           bool
	ReplyAuthorID          *int64
	ReplyAuthorUsername    *string
	ReplyAuthorDisplayName *string
}

// One message in the same shape as ListMessages.
func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (GetMessageRow, error) {
	row := q.db.QueryRow(ctx, getMessage, arg.ID, arg.ChannelID)
	var i GetMessageRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Content,
		&i.CreatedAt,
		&i.EditedAt,
		&i.AuthorID,
		&i.Deleted,
		&i.MentionsEveryone,
		&i.AuthorUsername,
		&i.AuthorDisplayName,
		&i.ReplyToID,
		&i.ReplyContent,
		&i.ReplyDeleted,
		&i.ReplyAuthorID,
		&i.ReplyAuthorUsername,
		&i.ReplyAuthorDisplayName,
	)
	return i, err
}

const getMessageWithAuthor = `-- name: GetMessageWithAuthor :one
SELECT m.id, m.channel_id, m.author_id, u.role AS author_role
FROM messages m
LEFT JOIN users u ON u.id = m.author_id
WHERE m.id = $1 AND m.channel_id = $2 AND m.deleted_at IS NULL
`

type GetMessageWithAuthorParams struct {
	ID        int64
	ChannelID int64
}

type GetMessageWithAuthorRow struct {
	ID         int64
	ChannelID  int64
	AuthorID   *int64
	AuthorRole *string
}

// A live (not deleted) message in a channel, with its author's role (for the hierarchy rule).
func (q *Queries) GetMessageWithAuthor(ctx context.Context, arg GetMessageWithAuthorParams) (GetMessageWithAuthorRow, error) {
	row := q.db.QueryRow(ctx, getMessageWithAuthor, arg.ID, arg.ChannelID)
	var i GetMessageWithAuthorRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.AuthorRole,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT
    c.id, c.name, c.topic, c.type, c.position, c.view_role, c.send_role,
    -- sqlc cannot tell that a LATERAL join may find nothing, so make "no message" explicit.
    (lm.created_at IS NOT NULL)::boolean        AS has_last_message,
    COALESCE(lm.content, '')::text            AS last_content,
    COALESCE(lm.created_at, now())::timestamptz AS last_created_at,
    u.display_name AS last_author
FROM channels c
LEFT JOIN LATERAL (
    SELECT m.content, m.created_at, m.author_id
    FROM messages m
    WHERE m.channel_id = c.id
      AND m.deleted_at IS NULL -- the preview shows the newest message that still has text
    ORDER BY m.id DESC
    LIMIT 1
) lm ON true
LEFT JOIN users u ON u.id = lm.author_id
ORDER BY c.position, c.id
`

type ListChannelsRow struct {
	ID             int64
	Name           string
	Topic          string
	Type           string
	Position       int32
	ViewRole       string
	SendRole       string
	HasLastMessage bool
	LastContent    string
	LastCreatedAt  time.Time
	LastAuthor     *string
}

// All channels in room-list order, each with its newest message (if any) for the preview.
func (q *Queries) ListChannels(ctx context.Context) ([]ListChannelsRow, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsRow
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Topic,
			&i.Type,
			&i.Position,
			&i.ViewRole,
			&i.SendRole,
			&i.HasLastMessage,
			&i.LastContent,
			&i.LastCreatedAt,
			&i.LastAuthor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentions = `-- name: ListMentions :many
SELECT mm.message_id, u.id, u.username, u.display_name
FROM message_mentions mm
JOIN users u ON u.id = mm.user_id
WHERE mm.message_id = ANY($1::bigint[])
ORDER BY mm.message_id, u.id
`

type ListMentionsRow struct {
	MessageID   int64
	ID          int64
	Username    string
	DisplayName string
}

// Who the given messages mention (for message objects).
func (q *Queries) ListMentions(ctx context.Context, messageIds []int64) ([]ListMentionsRow, error) {
	rows, err := q.db.Query(ctx, listMentions, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMentionsRow
	for rows.Next() {
		var i ListMentionsRow
		if err := rows.Scan(
			&i.MessageID,
			&i.ID,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT
    m.id, m.channel_id, m.content, m.created_at, m.edited_at, m.author_id,
    (m.deleted_at IS NOT NULL)::boolean AS deleted, m.mentions_everyone,
    u.username     AS author_username,
    u.display_name AS author_display_name,
    m.reply_to_id,
    r.content      AS reply_content,
    (r.deleted_at IS NOT NULL)::boolean AS reply_deleted,
    r.author_id    AS reply_author_id,
    ru.username     AS reply_author_username,
    ru.display_name AS reply_author_display_name
FROM messages m
LEFT JOIN users u ON u.id = m.author_id
LEFT JOIN messages r ON r.id = m.reply_to_id
LEFT JOIN users ru ON ru.id = r.author_id
WHERE m.channel_id = $1
  AND ($2::bigint IS NULL OR m.id < $2::bigint)
ORDER BY m.id DESC
LIMIT $3
`

type ListMessagesParams struct {
	ChannelID int64
	Before    *int64
	RowLimit  int32
}

type ListMessagesRow struct {
	ID                     int64
	ChannelID              int64
	Content                string
	CreatedAt              time.Time
	EditedAt               *time.Time
	AuthorID               *int64
	Deleted                bool
	MentionsEveryone       bool
	AuthorUsername         *string
	AuthorDisplayName      *string
	ReplyToID              *int64
	ReplyContent           *string
	ReplyDeleted           bool
	ReplyAuthorID          *int64
	ReplyAuthorUsername    *string
	ReplyAuthorDisplayName *string
}

// One page of history, NEWEST first. "before" is the id of the oldest message the
// client already has (NULL for the newest page). Keyset pagination: see docs.
// r / ru = the message this one replies to, and its author (all NULL if not a reply).
// Keep the column list identical to GetMessage (the Go code converts between the two).
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ChannelID, arg.Before, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Content,
			&i.CreatedAt,
			&i.EditedAt,
			&i.AuthorID,
			&i.Deleted,
			&i.MentionsEveryone,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.ReplyToID,
			&i.ReplyContent,
			&i.ReplyDeleted,
			&i.ReplyAuthorID,
			&i.ReplyAuthorUsername,
			&i.ReplyAuthorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRead = `-- name: MarkRead :one
INSERT INTO read_states (user_id, channel_id, last_read_id)
VALUES (
    $1, $2,
    LEAST($3::bigint,
          (SELECT COALESCE(MAX(id), 0) FROM messages WHERE channel_id = $2))
)
ON CONFLICT (user_id, channel_id)
DO UPDATE SET last_read_id = GREATEST(read_states.last_read_id, EXCLUDED.last_read_id)
RETURNING last_read_id
`

type MarkReadParams struct {
	UserID    int64
	ChannelID int64
	MessageID int64
}

// Moves the read marker forward (never back), and never past the newest message.
func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) (int64, error) {
	row := q.db.QueryRow(ctx, markRead, arg.UserID, arg.ChannelID, arg.MessageID)
	var last_read_id int64
	err := row.Scan(&last_read_id)
	return last_read_id, err
}

const mentionCandidates = `-- name: MentionCandidates :many

SELECT id, role FROM users
WHERE username = ANY($1::text[]) OR id = $2
`

type MentionCandidatesParams struct {
	Usernames     []string
	ReplyAuthorID int64
}

type MentionCandidatesRow struct {
	ID   int64
	Role string
}

// ---- mentions (M6) ----
// The users named in a message (@username), plus the author of the message it replies to.
func (q *Queries) MentionCandidates(ctx context.Context, arg MentionCandidatesParams) ([]MentionCandidatesRow, error) {
	rows, err := q.db.Query(ctx, mentionCandidates, arg.Usernames, arg.ReplyAuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MentionCandidatesRow
	for rows.Next() {
		var i MentionCandidatesRow
		if err := rows.Scan(&i.ID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replyTarget = `-- name: ReplyTarget :one
SELECT author_id FROM messages WHERE id = $1 AND channel_id = $2 AND deleted_at IS NULL
`

type ReplyTargetParams struct {
	ID        int64
	ChannelID int64
}

// A live (not deleted) message in this channel that a reply may point at, and its author.
func (q *Queries) ReplyTarget(ctx context.Context, arg ReplyTargetParams) (*int64, error) {
	row := q.db.QueryRow(ctx, replyTarget, arg.ID, arg.ChannelID)
	var author_id *int64
	err := row.Scan(&author_id)
	return author_id, err
}

const unreadCounts = `-- name: UnreadCounts :many

SELECT
    c.id AS channel_id,
    COALESCE(rs.last_read_id, 0)::bigint AS last_read_id,
    (SELECT COUNT(*) FROM (
        SELECT 1 FROM messages m
        WHERE m.channel_id = c.id AND m.id > COALESCE(rs.last_read_id, 0)
          AND m.created_at > u.created_at AND m.deleted_at IS NULL
          AND m.author_id IS DISTINCT FROM u.id
        LIMIT 100) x)::int AS unread_count,
    (SELECT COUNT(*) FROM (
        SELECT 1 FROM messages m
        WHERE m.channel_id = c.id AND m.id > COALESCE(rs.last_read_id, 0)
          AND m.created_at > u.created_at AND m.deleted_at IS NULL
          AND m.author_id IS DISTINCT FROM u.id
          AND (m.mentions_everyone OR EXISTS (
              SELECT 1 FROM message_mentions mm WHERE mm.message_id = m.id AND mm.user_id = u.id))
        LIMIT 100) y)::int AS mention_count
FROM channels c
JOIN users u ON u.id = $1
LEFT JOIN read_states rs ON rs.user_id = u.id AND rs.channel_id = c.id
`

type UnreadCountsRow struct {
	ChannelID    int64
	LastReadID   int64
	UnreadCount  int32
	MentionCount int32
}

// ---- unread (M6) ----
// Per channel, for one user: the last message they read, how many newer messages there
// are, and how many of those mention them. Their own messages, deleted messages, and
// messages from before their account existed never count. Counts stop at 100 (the
// client shows "99+"), so a huge backlog stays cheap to count.
func (q *Queries) UnreadCounts(ctx context.Context, userID int64) ([]UnreadCountsRow, error) {
	rows, err := q.db.Query(ctx, unreadCounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnreadCountsRow
	for rows.Next() {
		var i UnreadCountsRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.LastReadID,
			&i.UnreadCount,
			&i.MentionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels SET name = $2, topic = $3, view_role = $4, send_role = $5 WHERE id = $1
RETURNING id, name, topic, type, position, created_at, view_role, send_role
`

type UpdateChannelParams struct {
	ID       int64
	Name     string
	Topic    string
	ViewRole string
	SendRole string
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.Name,
		arg.Topic,
		arg.ViewRole,
		arg.SendRole,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.Position,
		&i.CreatedAt,
		&i.ViewRole,
		&i.SendRole,
	)
	return i, err
}
