// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingUploads = `-- name: CountPendingUploads :one
SELECT COUNT(*) FROM attachments WHERE uploader_id = $1 AND message_id IS NULL
`

// Uploads of a user not attached to a message yet (limits how much one user can park).
func (q *Queries) CountPendingUploads(ctx context.Context, uploaderID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingUploads, uploaderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (uploader_id, filename, content_type, size, width, height, storage_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, uploader_id, message_id, filename, content_type, size, width, height, storage_key, created_at
`

type CreateAttachmentParams struct {
	UploaderID  *int64
	Filename    string
	ContentType string
	Size        int64
	Width       pgtype.Int4
	Height      pgtype.Int4
	StorageKey  string
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.UploaderID,
		arg.Filename,
		arg.ContentType,
		arg.Size,
		arg.Width,
		arg.Height,
		arg.StorageKey,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.MessageID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessageAttachments = `-- name: DeleteMessageAttachments :exec
DELETE FROM attachments WHERE message_id = $1
`

// A deleted message loses its files (the files on disk are removed by the cleanup).
func (q *Queries) DeleteMessageAttachments(ctx context.Context, messageID *int64) error {
	_, err := q.db.Exec(ctx, deleteMessageAttachments, messageID)
	return err
}

const deleteStaleUploads = `-- name: DeleteStaleUploads :execrows
DELETE FROM attachments WHERE message_id IS NULL AND created_at < now() - interval '1 hour'
`

// Uploads never attached to a message within an hour.
func (q *Queries) DeleteStaleUploads(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleUploads)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const existingStorageKeys = `-- name: ExistingStorageKeys :many
SELECT storage_key FROM attachments WHERE storage_key = ANY($1::text[])
`

// Which of these files on disk still belong to an attachment.
func (q *Queries) ExistingStorageKeys(ctx context.Context, keys []string) ([]string, error) {
	rows, err := q.db.Query(ctx, existingStorageKeys, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttachmentForDownload = `-- name: GetAttachmentForDownload :one
SELECT a.id, a.uploader_id, a.message_id, a.filename, a.content_type, a.size, a.width, a.height, a.storage_key, a.created_at, m.channel_id, (m.deleted_at IS NOT NULL)::boolean AS message_deleted
FROM attachments a
LEFT JOIN messages m ON m.id = a.message_id
WHERE a.id = $1
`

type GetAttachmentForDownloadRow struct {
	ID             int64
	UploaderID     *int64
	MessageID      *int64
	Filename       string
	ContentType    string
	Size           int64
	Width          pgtype.Int4
	Height         pgtype.Int4
	StorageKey     string
	CreatedAt      time.Time
	ChannelID      *int64
	MessageDeleted bool
}

// The attachment, plus where its message lives (NULL if not attached yet).
func (q *Queries) GetAttachmentForDownload(ctx context.Context, id int64) (GetAttachmentForDownloadRow, error) {
	row := q.db.QueryRow(ctx, getAttachmentForDownload, id)
	var i GetAttachmentForDownloadRow
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.MessageID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.StorageKey,
		&i.CreatedAt,
		&i.ChannelID,
		&i.MessageDeleted,
	)
	return i, err
}

const linkAttachments = `-- name: LinkAttachments :many
UPDATE attachments SET message_id = $1
WHERE id = ANY($2::bigint[])
  AND uploader_id = $3
  AND message_id IS NULL
RETURNING id
`

type LinkAttachmentsParams struct {
	MessageID  *int64
	Ids        []int64
	UploaderID *int64
}

// Attaches the user's own, still unattached uploads to a message. The caller checks that
// every requested id came back (anything else is someone else's, used, or unknown).
func (q *Queries) LinkAttachments(ctx context.Context, arg LinkAttachmentsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, linkAttachments, arg.MessageID, arg.Ids, arg.UploaderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachments = `-- name: ListAttachments :many
SELECT id, message_id, filename, content_type, size, width, height
FROM attachments
WHERE message_id = ANY($1::bigint[])
ORDER BY id
`

type ListAttachmentsRow struct {
	ID          int64
	MessageID   *int64
	Filename    string
	ContentType string
	Size        int64
	Width       pgtype.Int4
	Height      pgtype.Int4
}

// The attachments of the given messages, for message objects.
func (q *Queries) ListAttachments(ctx context.Context, messageIds []int64) ([]ListAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listAttachments, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsRow
	for rows.Next() {
		var i ListAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
