// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"
	"time"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (code_hash, created_by, max_uses, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, code_hash, created_by, max_uses, uses, expires_at, created_at
`

type CreateInviteParams struct {
	CodeHash  []byte
	CreatedBy int64
	MaxUses   int32
	ExpiresAt time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.CodeHash,
		arg.CreatedBy,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :execrows
DELETE FROM invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listInvites = `-- name: ListInvites :many
SELECT id, code_hash, created_by, max_uses, uses, expires_at, created_at FROM invites ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.CodeHash,
			&i.CreatedBy,
			&i.MaxUses,
			&i.Uses,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
