// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"
)

const banUser = `-- name: BanUser :exec
UPDATE users SET banned_at = now(), ban_reason = $2 WHERE id = $1
`

type BanUserParams struct {
	ID        int64
	BanReason string
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.Exec(ctx, banUser, arg.ID, arg.BanReason)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, display_name, password_hash, created_at, role, banned_at, ban_reason FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.BannedAt,
		&i.BanReason,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, password_hash, created_at, role, banned_at, ban_reason FROM users ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.Role,
			&i.BannedAt,
			&i.BanReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :execrows
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

// Signs a user out everywhere (kick, ban).
func (q *Queries) RevokeUserSessions(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users SET role = $2 WHERE id = $1 RETURNING id, username, display_name, password_hash, created_at, role, banned_at, ban_reason
`

type SetUserRoleParams struct {
	ID   int64
	Role string
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.BannedAt,
		&i.BanReason,
	)
	return i, err
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE users SET banned_at = NULL, ban_reason = '' WHERE id = $1
`

func (q *Queries) UnbanUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, unbanUser, id)
	return err
}
