// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID          int64
	UploaderID  *int64
	MessageID   *int64
	Filename    string
	ContentType string
	Size        int64
	Width       pgtype.Int4
	Height      pgtype.Int4
	StorageKey  string
	CreatedAt   time.Time
}

type Channel struct {
	ID        int64
	Name      string
	Topic     string
	Type      string
	Position  int32
	CreatedAt time.Time
	ViewRole  string
	SendRole  string
}

type Invite struct {
	ID        int64
	CodeHash  []byte
	CreatedBy int64
	MaxUses   int32
	Uses      int32
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Message struct {
	ID               int64
	ChannelID        int64
	AuthorID         *int64
	Content          string
	CreatedAt        time.Time
	DeletedAt        *time.Time
	DeletedBy        *int64
	ReplyToID        *int64
	EditedAt         *time.Time
	MentionsEveryone bool
}

type MessageMention struct {
	MessageID int64
	UserID    int64
}

type ReadState struct {
	UserID     int64
	ChannelID  int64
	LastReadID int64
}

type Session struct {
	ID         int64
	UserID     int64
	TokenHash  []byte
	CreatedAt  time.Time
	LastUsedAt time.Time
	ExpiresAt  time.Time
	RevokedAt  *time.Time
}

type User struct {
	ID           int64
	Username     string
	DisplayName  string
	PasswordHash string
	CreatedAt    time.Time
	Role         string
	BannedAt     *time.Time
	BanReason    string
	AvatarKey    *string
}
