// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Channel struct {
	ID        int64
	Name      string
	Topic     string
	Type      string
	Position  int32
	CreatedAt time.Time
}

type Invite struct {
	ID        int64
	CodeHash  []byte
	CreatedBy int64
	MaxUses   int32
	Uses      int32
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Message struct {
	ID        int64
	ChannelID int64
	AuthorID  *int64
	Content   string
	CreatedAt time.Time
}

type Session struct {
	ID         int64
	UserID     int64
	TokenHash  []byte
	CreatedAt  time.Time
	LastUsedAt time.Time
	ExpiresAt  time.Time
	RevokedAt  *time.Time
}

type User struct {
	ID           int64
	Username     string
	DisplayName  string
	PasswordHash string
	IsOwner      bool
	CreatedAt    time.Time
}
