// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package db

import (
	"context"
)

const postgresVersion = `-- name: PostgresVersion :one
SELECT version()::text AS version
`

// Returns the PostgreSQL version text. Logged at startup.
func (q *Queries) PostgresVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, postgresVersion)
	var version string
	err := row.Scan(&version)
	return version, err
}
